services:
  backend:
    build: ./backend
    container_name: rust-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data  

  frontend:
    build: ./frontend
    container_name: leptos-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:8000 